---
title: Guide d'utilisation des données du recensement de la population au format `Parquet`
#embed-resources: true
code-annotations: true
date: 2023-10-18
bibliography: reference.bib
format:
  html: default
---

Ce guide présente quelques exemples d'utilisation des données du 
recensement de la population diffusées au format `Parquet`. 

Pour plus d'informations sur le format `Parquet`, dans un contexte
de statistique publique, se référer à @dondon-lamarche-2023. Pour
un exemple sur la différence entre format `CSV` et `Parquet`
illustré sur les données du recensement de la population, voir @mauviere-2022.

Ce guide propose d'utiliser [`DuckDB`](https://duckdb.org/) à travers
plusieurs langages pour effectuer des traitements sur les fichiers
détails du recensement. Par rapport à d'autres approches, [`DuckDB`](https://duckdb.org/) a été choisi pour son efficacité ainsi que pour son universalité.

L'ensemble des codes utilisés pour produire cette note
est disponible sur le
dépôt [`Github` InseeFrLab/exemples-recensement-parquet](https://github.com/InseeFrLab/exemples-recensement-parquet)
au format [`Quarto Markdown`](https://quarto.org/).

::: {.callout-note}
Ce _post_ accompagne la mise à disposition des données
du recensement de la population au format `Parquet`
sur le site [insee.fr](https://www.insee.fr/fr/statistiques/7706119?sommaire=7637890).

Il vise à fournir
une expérience plus ergonomique et des exemples supplémentaires liés
au langage `Javascript` au guide PDF disponible sur la page du site
[insee.fr](https://www.insee.fr/fr/statistiques/7706119?sommaire=7637890)
:::


{{< include "snippets/1_create_db_ojs.qmd" >}}

{{< include "snippets/2_select_schema_ojs.qmd" >}}

{{< include "snippets/3_select_documentation_ojs.qmd" >}}

{{< include "snippets/4_selectz_ojs.qmd" >}}

{{< include "snippets/5_limit_ojs.qmd" >}}

{{< include "snippets/5_sample_ojs.qmd" >}}

{{< include "snippets/6_sample_columns_ojs.qmd" >}}

{{< include "snippets/7_use_regex_ojs.qmd" >}}

{{< include "snippets/8_filter_dates_ojs.qmd" >}}

{{< include "snippets/8_filter_dpts_ojs.qmd" >}}

{{< include "snippets/8_filter_regions_ojs.qmd" >}}

{{< include "snippets/9_distinct_arrondissements_ojs.qmd" >}}

{{< include "snippets/10_use_cast_ojs.qmd" >}}

{{< include "snippets/11_pyramide_ages_ojs.qmd" >}}

fff
s